version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        ports:
            - 9200:9200
            - 9300:9300
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

volumes: 
    elasticsearch_data: