name: CI

on:
    push:
        branches: [ main, develop, feat/*, fix/* ]
    pull_request:
        branches: [ main, develop, feat/* ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Black Code Formatter
                uses: lgeiger/black-action@master
                with:
                    args: ". --check"
